# Generated by Django 4.2.4 on 2023-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Purchases', 'Purchases'), ('Selling', 'Selling')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.FileField(default='', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ads',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
