# Generated by Django 4.2.4 on 2023-08-31 22:20

import ads.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_ads_category_ads_description_ads_image_ads_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ads.models.image_upload),
        ),
    ]
