# Generated by Django 4.2.4 on 2023-08-31 23:16

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_user_alter_ads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(default='', upload_to=ads.models.image_upload),
            preserve_default=False,
        ),
    ]
